import '@testing-library/jest-dom'
import { vi } from 'vitest'

// jsdom throws SecurityError for localStorage on opaque origins — provide a simple mock
const localStorageMock = (() => {
  let store = {}
  return {
    getItem: (key) => Object.prototype.hasOwnProperty.call(store, key) ? store[key] : null,
    setItem: (key, value) => { store[key] = String(value) },
    removeItem: (key) => { delete store[key] },
    clear: () => { store = {} },
  }
})()
Object.defineProperty(window, 'localStorage', { value: localStorageMock, writable: true })

const { mockChangeLanguage, mockT } = vi.hoisted(() => ({
  mockChangeLanguage: vi.fn(() => new Promise(() => {})),
  mockT: (key, options) => {
    const translations = {
      'nav.features': 'Features',
      'nav.screenshots': 'Screenshots',
      'nav.reviews': 'Reviews',
      'nav.clientPortal': 'Espace Client',
      'hero.badge': 'Now available on iOS & Android',
      'hero.headline': 'Find Your Perfect Home with AI',
      'hero.subtitle': 'AI-powered property search, immersive virtual tours, and real-time market insights — all in one beautifully simple app.',
      'hero.stats.rating': 'App Store Rating',
      'hero.stats.users': 'Happy Users',
      'hero.stats.market': 'Real Estate App',
      'features.tag': 'Features',
      'features.title': 'Everything you need to find home',
      'features.subtitle': 'Powerful tools designed to make your property search faster, smarter, and less stressful.',
      'features.list.search.title': 'AI-Powered Search',
      'features.list.tours.title': 'Virtual Tours',
      'features.list.insights.title': 'Market Insights',
      'features.list.alerts.title': 'Instant Alerts',
      'features.list.connect.title': 'Agent Connect',
      'features.list.guide.title': 'Neighborhood Guide',
      'screenshots.title': 'Beautiful by design',
      'screenshots.subtitle': 'Every screen crafted for clarity. Powerful features delivered through a clean, intuitive interface.',
      'testimonials.title': 'Loved by home seekers',
      'testimonials.subtitle': 'Join 50,000+ people who found their perfect home with Klipp.',
      'testimonials.list.0.quote': "Klipp made finding our first home feel effortless. The AI search understood exactly what we wanted — we found our place in two weeks instead of six months.",
      'testimonials.list.0.role': 'First-time homebuyer, Austin TX',
      'testimonials.list.1.quote': "As a real estate agent, I recommend Klipp to all my clients. The virtual tours alone save us dozens of hours per deal. The market data is genuinely best-in-class.",
      'testimonials.list.1.role': 'Licensed Real Estate Agent, NYC',
      'testimonials.list.2.quote': "Relocated from Seattle to Miami for work. Used Klipp to scope out neighborhoods remotely — the neighborhood guides and virtual tours were absolutely invaluable.",
      'testimonials.list.2.role': 'Remote buyer, Miami FL',
      'download.title': 'Start your search today',
      'download.subtitle': 'Download Klipp free and find your perfect property. No subscription required.',
      'download.appStore': 'Download on the App Store',
      'download.googlePlay': 'Get it on Google Play',
      'download.disclaimer': 'Free to download · Available on iOS 16+ & Android 8+',
      'footer.description': 'Find your perfect home with AI-powered search and real-time market insights.',
      'footer.sections.Product': 'Product',
      'footer.sections.Company': 'Company',
      'footer.sections.Legal': 'Legal',
      'footer.links.Features': 'Features',
      'footer.links.Screenshots': 'Screenshots',
      'footer.links.Pricing': 'Pricing',
      'footer.links.Changelog': 'Changelog',
      'footer.links.About': 'About',
      'footer.links.Blog': 'Blog',
      'footer.links.Careers': 'Careers',
      'footer.links.Press': 'Press',
      'footer.links.Privacy Policy': 'Privacy Policy',
      'footer.links.Terms of Service': 'Terms of Service',
      'footer.links.Cookie Policy': 'Cookie Policy',
      'footer.copyright': '© 2026 Klipp. All rights reserved.',
      'cookies.title': 'Cookies & préférences',
      'cookies.description': 'Nous utilisons des cookies pour mémoriser votre préférence de thème (clair/sombre). Aucune donnée personnelle n\'est collectée.',
      'cookies.accept': 'Accepter',
      'cookies.decline': 'Refuser',
      'portal.backToHome': 'Back to home',
      'portal.login.title': 'Welcome back',
      'portal.login.subtitle': 'Sign in to your agency account',
      'portal.login.emailLabel': 'Email',
      'portal.login.emailPlaceholder': 'agency@example.com',
      'portal.login.passwordLabel': 'Password',
      'portal.login.passwordPlaceholder': 'Your password',
      'portal.login.submit': 'Sign in',
      'portal.login.loading': 'Signing in…',
      'portal.login.noAccount': "Don't have an account?",
      'portal.login.registerLink': 'Create one',
      'portal.login.errorGeneric': 'An error occurred. Please try again.',
      'portal.register.title': 'Create your account',
      'portal.register.subtitle': 'Register your agency on Klipp',
      'portal.register.agencyNameLabel': 'Agency name',
      'portal.register.agencyNamePlaceholder': 'My Agency',
      'portal.register.managerNameLabel': 'Manager name',
      'portal.register.managerNamePlaceholder': 'John Doe',
      'portal.register.emailLabel': 'Email',
      'portal.register.emailPlaceholder': 'agency@example.com',
      'portal.register.passwordLabel': 'Password',
      'portal.register.confirmPasswordLabel': 'Confirm password',
      'portal.register.phoneLabel': 'Phone',
      'portal.register.streetNumberLabel': 'No.',
      'portal.register.streetLabel': 'Street',
      'portal.register.streetPlaceholder': 'Rue de la Paix',
      'portal.register.postalCodeLabel': 'Postal code',
      'portal.register.cityLabel': 'City',
      'portal.register.cityPlaceholder': 'Paris',
      'portal.register.submit': 'Create account',
      'portal.register.loading': 'Creating…',
      'portal.register.hasAccount': 'Already have an account?',
      'portal.register.loginLink': 'Sign in',
      'portal.register.errorPasswordMismatch': 'Passwords do not match.',
      'portal.register.errorGeneric': 'An error occurred. Please try again.',
      'portal.dashboard.logout': 'Sign out',
      'portal.dashboard.nav.dashboard': 'Dashboard',
      'portal.dashboard.nav.profile': 'Agency profile',
      'portal.dashboard.chart.title': 'Sales — Last 30 days',
      'portal.dashboard.chart.sales_one': 'Sale',
      'portal.dashboard.chart.sales_other': 'Sales',
      'portal.dashboard.stats.messages.label': 'Messages',
      'portal.dashboard.stats.messages.value': '0',
      'portal.dashboard.stats.activeListings.label': 'Active listings',
      'portal.dashboard.stats.activeListings.value': '0',
      'portal.dashboard.stats.monthlySales.label': 'Sales this month',
      'portal.dashboard.stats.monthlySales.value': '0',
      'portal.profile.title': 'Agency profile',
      'portal.profile.agencyInfoSection': 'Agency information',
      'portal.profile.passwordSection': 'Change password',
      'portal.profile.managerNameLabel': 'Manager name',
      'portal.profile.agencyNameLabel': 'Agency name',
      'portal.profile.emailLabel': 'Email',
      'portal.profile.phoneLabel': 'Phone',
      'portal.profile.streetNumberLabel': 'No.',
      'portal.profile.streetLabel': 'Street',
      'portal.profile.postalCodeLabel': 'Postal code',
      'portal.profile.cityLabel': 'City',
      'portal.profile.saveInfo': 'Save changes',
      'portal.profile.savePassword': 'Update password',
      'portal.profile.currentPasswordLabel': 'Current password',
      'portal.profile.newPasswordLabel': 'New password',
      'portal.profile.confirmNewPasswordLabel': 'Confirm new password',
      'portal.profile.loading': 'Saving…',
      'portal.profile.errorPasswordMismatch': 'Passwords do not match.',
      'portal.profile.errorGeneric': 'An error occurred. Please try again.',
      'portal.profile.successInfo': 'Information updated successfully.',
      'portal.profile.successPassword': 'Password updated successfully.',
      'portal.profile.deleteSection': 'Danger zone',
      'portal.profile.deleteDescription': 'Once you delete your account, all your data will be permanently removed. This action cannot be undone.',
      'portal.profile.deleteButton': 'Delete account',
      'portal.profile.deleteModalTitle': 'Delete account',
      'portal.profile.deleteModalWarning': 'This action is irreversible and will permanently delete all your data.',
      'portal.profile.deleteModalInstruction': 'Type your agency name to confirm:',
      'portal.profile.deleteModalConfirm': 'Delete account',
      'portal.profile.deleteModalCancel': 'Cancel',
      'legal.lastUpdated': 'Last updated: {{date}}',
      'legal.privacy.title': 'Privacy Policy',
      'legal.privacy.intro': 'This policy explains what personal data {{company}} collects through the Klipp website, the agency portal and the Klipp mobile app, why it is collected and what your rights are.',
      'legal.privacy.sections.controller.title': '1. Data controller',
      'legal.privacy.sections.controller.body': 'The data controller is {{company}}, with its registered office at {{address}}.\nFor any question about your data, you can contact us at {{email}}.',
      'legal.privacy.sections.data.title': '2. Data we collect',
      'legal.privacy.sections.data.body': "Website: no personal data is collected apart from the preference cookies described below.\n\nAgency portal: when you create and use your account, we collect the agency name, the manager's name, email address, phone number, postal address and password.\n\nAgents and offices: the information your agency enters about its agents (photo, name, email, phone) and its offices (photo, name, address, email, phone).",
      'legal.privacy.sections.purposes.title': '3. Purposes and legal bases',
      'legal.privacy.sections.purposes.body': '• Creating and managing your agency account — performance of contract.\n• Displaying your agents and offices in the Klipp app — performance of contract.\n• Service security and abuse prevention — legitimate interest.\n• Remembering your preferences (theme, language) — consent.',
      'legal.privacy.sections.retention.title': '4. Retention',
      'legal.privacy.sections.retention.body': 'Account data is kept for as long as your account is active. When you delete your account from your profile, your data and that of your agents and offices is deleted, subject to legal retention obligations.\nPreference cookies are kept for a maximum of 12 months.',
      'legal.privacy.sections.recipients.title': '5. Recipients and hosting',
      'legal.privacy.sections.recipients.body': "Your data is intended solely for {{company}} and is never sold. It is hosted by {{host}}.\nWhere data is transferred outside the European Union, the transfer is covered by appropriate safeguards, such as the European Commission's standard contractual clauses.",
      'legal.privacy.sections.cookies.title': '6. Cookies and local storage',
      'legal.privacy.sections.cookies.body': "We use no advertising or analytics cookies.\n\n• cookie_consent — remembers your cookie choice (12 months).\n• theme — remembers light or dark theme, only if you accepted cookies (12 months).\n• i18next — remembers your language, only if you accepted cookies (12 months).\n\nWhen you are signed in to the agency portal, your session token is kept in your browser's local storage. It is strictly necessary for the service to work and is removed when you sign out.",
      'legal.privacy.sections.rights.title': '7. Your rights',
      'legal.privacy.sections.rights.body': 'Under the GDPR, you have the right to access, rectify, erase, restrict, port and object to the processing of your data, as well as the right to withdraw your consent at any time.\nTo exercise these rights, write to {{email}}. You may also lodge a complaint with the CNIL (www.cnil.fr).',
      'legal.privacy.sections.security.title': '8. Security',
      'legal.privacy.sections.security.body': 'We implement appropriate technical and organisational measures to protect your data against unauthorised access, loss or alteration. Traffic between your browser and our servers is encrypted (HTTPS).',
      'legal.privacy.sections.changes.title': '9. Changes',
      'legal.privacy.sections.changes.body': 'We may update this policy. The date of the last update is shown at the top of this page. If we make significant changes, we will notify you by email or through the agency portal.',
      'legal.terms.title': 'Terms of Service',
      'legal.terms.intro': 'These terms govern access to and use of the Klipp website, the agency portal and the Klipp mobile app. By using our services, you accept them in full.',
      'legal.terms.sections.publisher.title': '1. Publisher and host',
      'legal.terms.sections.publisher.body': 'The service is published by {{company}}, with its registered office at {{address}}. Contact: {{email}}.\nPublication director: {{director}}.\nThe website is hosted by {{host}}.',
      'legal.terms.sections.service.title': '2. The service',
      'legal.terms.sections.service.body': 'Klipp is a real estate search app. The agency portal lets real estate agencies manage their profile, agents and offices, and view their statistics.',
      'legal.terms.sections.account.title': '3. Agency account',
      'legal.terms.sections.account.body': 'Agency accounts are reserved for real estate professionals. You agree to provide accurate information and keep it up to date.\nYou are responsible for keeping your credentials confidential and for all activity on your account. Notify us promptly of any unauthorised use.',
      'legal.terms.sections.obligations.title': '4. Agency obligations',
      'legal.terms.sections.obligations.body': 'You agree to use the service lawfully and not to publish any unlawful or misleading content, or content that infringes the rights of others.\nWhen you add agents, you warrant that you have informed them and have a legal basis to publish their data (photo, name, contact details).',
      'legal.terms.sections.ip.title': '5. Intellectual property',
      'legal.terms.sections.ip.body': 'The Klipp brand, website, app and all their content (text, visuals, logos, code) are the property of {{company}}. Any reproduction without permission is prohibited.\nYou keep the rights to the content you publish and grant us a non-exclusive licence to display it as part of the service.',
      'legal.terms.sections.liability.title': '6. Liability',
      'legal.terms.sections.liability.body': 'We strive to keep the service available and working properly but cannot guarantee it absolutely. The service may be interrupted for maintenance or in case of force majeure.\n{{company}} is not liable for content published by agencies or for indirect damages resulting from use of the service.',
      'legal.terms.sections.termination.title': '7. Suspension and termination',
      'legal.terms.sections.termination.body': 'You can delete your account at any time from your profile. We may suspend or delete an account that breaches these terms, after notifying the agency where possible.',
      'legal.terms.sections.data.title': '8. Personal data',
      'legal.terms.sections.data.body': 'How we process your personal data is described in our privacy policy.',
      'legal.terms.sections.changes.title': '9. Changes to these terms',
      'legal.terms.sections.changes.body': 'We may change these terms at any time. New terms apply as soon as they are published on this page. If we make significant changes, we will notify you in advance.',
      'legal.terms.sections.law.title': '10. Governing law',
      'legal.terms.sections.law.body': 'These terms are governed by French law. In the event of a dispute, an amicable solution will be sought first; failing that, the French courts shall have sole jurisdiction.',
      'portal.agents.form.office': 'Physical office',
      'portal.agents.form.officeNone': 'No office assigned',
      'portal.agents.list.pending': 'Pending',
      'portal.agents.list.delete': 'Delete',
      'portal.agents.deleteModal.title': 'Delete agent?',
      'portal.agents.deleteModal.message': 'Are you sure you want to delete "{{name}}"? This action cannot be undone.',
      'portal.agents.deleteModal.cancel': 'Cancel',
      'portal.agents.deleteModal.confirm': 'Delete',
      'portal.offices.deleteModal.title': 'Delete office?',
      'portal.offices.deleteModal.message': 'Are you sure you want to delete "{{name}}"? This action cannot be undone.',
      'portal.offices.deleteModal.cancel': 'Cancel',
      'portal.offices.deleteModal.confirm': 'Delete',
      'setPassword.loading': 'Verifying invitation…',
      'setPassword.invalidTitle': 'Invalid or expired link',
      'setPassword.invalidMessage': 'This invitation link is no longer valid. Please contact your agency.',
      'setPassword.title': 'Create your password',
      'setPassword.subtitle': 'Welcome, {{name}}. Choose a password to activate your account.',
      'setPassword.emailLabel': 'Email address',
      'setPassword.passwordLabel': 'Password',
      'setPassword.confirmLabel': 'Confirm password',
      'setPassword.submit': 'Create password',
      'setPassword.submitting': 'Saving…',
      'setPassword.errorMismatch': 'Passwords do not match.',
      'setPassword.errorGeneric': 'An error occurred. Please try again.',
      'setPassword.successTitle': 'Password created!',
      'setPassword.successMessage': 'Your password has been set successfully. You can now use the mobile app.',
      'portal.agents.list.linkPending': 'Invitation sent',
      'portal.agents.linkModal.title': 'Account already exists',
      'portal.agents.linkModal.message': 'A Klipp account already uses {{email}}. Do you want to invite this person to join your agency as an agent? They will receive an email and must accept before their account is linked.',
      'portal.agents.linkModal.cancel': 'Cancel',
      'portal.agents.linkModal.confirm': 'Send invitation',
      'setPassword.linkTitle': 'Join {{agency}}',
      'setPassword.linkMessage': 'Hello {{name}}, {{agency}} wants to link your Klipp account ({{email}}) to its agency as an agent. Your account and password stay the same.',
      'setPassword.linkAccept': 'Accept and become an agent',
      'setPassword.linkSuccessTitle': 'You are now an agent!',
      'setPassword.linkSuccessMessage': 'Your account is now linked to {{agency}}. Sign in to the mobile app as usual.',
    }
    if (key === 'portal.dashboard.greeting') {
      return `Hello, ${options?.agency ?? ''}`
    }
    if (key === 'portal.dashboard.chart.sales') {
      return options?.count === 1 ? 'Sale' : 'Sales'
    }
    return translations[key] || key
  }
}))

// Mock react-i18next
vi.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: mockT,
    i18n: {
      changeLanguage: mockChangeLanguage,
      language: 'en',
    },
  }),
  initReactI18next: {
    type: '3rdParty',
    init: () => {},
  },
  Trans: ({ i18nKey, children }) => {
    if (children) return children
    const translations = {
      'hero.headline': 'Find Your Perfect Home with AI',
    }
    return translations[i18nKey] || i18nKey
  },
}))
